import React, { createContext, useContext, useState, useEffect } from "react";

// Add new translation key for employee profile

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Login Page
    "login.welcome": "Welcome to NOC",
    "login.subtitle": "Empowering Efficiency, Ensuring Reliability",
    "login.email": "Email",
    "login.emailPlaceholder": "user@example.com",
    "login.password": "Password",
    "login.passwordPlaceholder": "••••••",
    "login.forgotPassword": "Forget Password?",
    "login.signIn": "Sign In",
    "login.signingIn": "Signing in...",
    "login.success": "Success",
    "login.loginSuccessful": "Login successful!",
    "login.error": "Error",
    "login.loginFailed": "Login failed. Please check your credentials.",
    "login.networkError": "Network error. Please try again.",
    language: "English",
    // Dashboard Page
    "dashboard.hello": "Hello,",
    "dashboard.dashboard": "Dashboard",
    "dashboard.attendance": "Attendance",
    "dashboard.quickCheckIn": "Quick Check-In",
    "dashboard.scanQR": "Scan QR to clock in/out",
    "dashboard.todaysHours": "Today's Hours",
    "dashboard.checkedIn": "Checked In",
    "dashboard.notStarted": "Not Started",
    "dashboard.checkOut": "Check Out",
    "dashboard.checkIn": "Check In",
    "dashboard.shift": "Shift: 09:00 AM - 06:00 PM",
    "dashboard.modules": "Modules",
    "dashboard.search": "Search",
    "dashboard.seeAll": "See All",
    "dashboard.timeTracker": "Time Tracker",
    "dashboard.timeOff": "Time Off",
    "dashboard.courses": "Courses",
    "dashboard.expenses": "Expenses",
    "dashboard.viewRequest": "View Request",
    "dashboard.documents": "Documents",
    "dashboard.signedDocuments": "Signed Documents",
    "dashboard.calendar": "Calendar",
    "dashboard.toDo": "To Do",
    "dashboard.timesheets": "Timesheets",
    "dashboard.surveys": "Surveys",
    "dashboard.appraisals": "Appraisals",
    "dashboard.fleet": "Fleet",
    "dashboard.ongoingTasks": "Ongoing Tasks",
    "dashboard.recentProjects": "Recent Projects",
    "dashboard.welcome": "Welcome",
    "dashboard.checkedInToast": "Checked In",
    "dashboard.checkedInDesc": "Your attendance has been recorded.",
    "dashboard.checkedOutToast": "Checked Out",
    "dashboard.checkedOutDesc": "Have a great day!",
    "dashboard.timeOffCount": "4 Time Off",
    "dashboard.requestsCount": "0 Requests",
    "dashboard.expensesCount": "16 Expenses",
    "dashboard.tasksCount": "18 Tasks",
    // More Page
    "more.myProfile": "My Profile",
    "more.myDashboard": "My Dashboard",
    "more.language": "Language",
    "more.myCourses": "My Courses",
    "more.privacyPolicy": "Privacy Policy",
    "more.termsAndConditions": "Terms And Conditions",
    "more.logOut": "Log Out",
    // Profile Page
    "profile.title": "Profile",
    "profile.employeeProfile": "Employee Profile",
    "profile.resume": "Resume",
    "profile.workInfo": "Work Info",
    "profile.privateInfo": "Private Info",
    "profile.myAchievement": "My Achievement",
    "profile.competencies": "Competencies",
    "profile.workExperience": "Work Experience",
    "profile.skills": "Skills",
    "profile.privateContact": "Private Contact",
    "profile.workAddress": "Work Address",
    "profile.workLocation": "Work Location",
    "profile.approvers": "Approvers",
    "profile.expenses": "Expenses",
    "profile.timeOff": "Time Off",
    "profile.timeSheet": "Time Sheet",
    "profile.attendance": "Attendance",
    "profile.schedule": "Schedule",
    "profile.workingHours": "Working Hours",
    "profile.workLocationPlan": "Work Location Plan",
    "profile.timeZone": "Time Zone",
    "profile.planning": "Planning",
    "profile.noRoles": "No Roles",
    "profile.organizationChart": "Organization Chart",
    "profile.seeAll": "See All",
    "profile.roles": "Roles",
    "profile.manager": "Manager",
    "profile.jobDescription": "Job Description",
    "profile.noJobDescription": "No job description available",
    "profile.privateAddress": "Private Address",
    "profile.email": "Email",
    "profile.phone": "Phone",
    "profile.bankAccountNumber": "Bank Account Number",
    "profile.language": "Language",
    "profile.homeWorkDistance": "Home Work Distance",
    "profile.privateCarPlate": "Private Car Plate",
    "profile.familyStatus": "Family Status",
    "profile.maritalStatus": "Marital Status",
    "profile.maritalStatus.title": "Marital Status",
    "profile.maritalStatus.single": "Single",
    "profile.maritalStatus.married": "Married",
    "profile.maritalStatus.cohabitant": "Legal Cohabitant",
    "profile.maritalStatus.widower": "Widower",
    "profile.maritalStatus.divorced": "Divorced",
    "profile.numberOfChildren": "Number of Children",
    "profile.emergency": "Emergency",
    "profile.contactName": "Contact Name",
    "profile.contactPhone": "Contact Phone",
    "profile.education": "Education",
    "profile.certificateLevel": "Certificate Level",
    "profile.certificateLevel.graduate": "Graduate",
    "profile.certificateLevel.bachelor": "Bachelor",
    "profile.certificateLevel.master": "Master",
    "profile.certificateLevel.doctor": "Doctor",
    "profile.fieldOfStudy": "Field of Study",
    "profile.school": "School",
    "profile.getLevelUp": "Get",
    "profile.xpToLevelUp": "xp to level up!",
    "profile.badges": "Badges",
    "profile.noBadges": "No badges earned yet",
    "profile.current": "Current",
    "profile.rejectReason": "Reject Reason",
    "profile.submissionApproved": "Your submission was approved by your manager.",
    "profile.submissionPending": "Your submission is being reviewed.",
    "profile.modified": "Modified",
    "profile.changesMade": "Changes made! Remember to submit them for review when you're done.",
    "profile.changesSaved": "Changes saved locally",
    "profile.submittedForReview": "Your changes have been submitted for review.",
    "profile.submitFailed": "Failed to submit changes. Please try again.",
    "common.save": "Save",
    "common.submit": "Submit",
    "common.submitting": "Submitting...",
    "common.success": "Success",
    "common.error": "Error",
    // Notifications Page
    "notifications.title": "Notifications",
    "notifications.notificationsTab": "Notifications",
    "notifications.modulesTab": "Modules",
    "notifications.appraisalToFill": "Appraisal to fill",
    "notifications.appraisalFor": "Appraisal for",
    "notifications.appraisalDesc": "Your appraisal is created and you can fill it here.",
    "notifications.annualLeaveRequest": "New Annual Leave Request created by",
    "notifications.timeOff": "Time Off",
    "notifications.employeeAppraisal": "Employee Appraisal",
    "notifications.approve": "Approve",
    "notifications.today": "Today",
    "notifications.future": "Future",
    // Employee 360
    "employee360.title": "Employee 360",
    "employee360.showing": "Showing",
    "employee360.of": "of",
    "employee360.employees": "employees",
    "employee360.loading": "Loading...",
    "employee360.loadMore": "Load More",
    "employee360.noEmployees": "No employees found",
    "employee360.submitted": "Submitted",
    "employee360.approved": "Approved",
    "employee360.rejected": "Rejected",
    "employee360.review": "Review",
    "employee360.approve": "Approve",
    "employee360.reject": "Reject",
    "employee360.viewSubmission": "View Submission",
    "employee360.confirmApprove": "Confirm Approval",
    "employee360.confirmApproveDescription": "Are you sure you want to approve this submission for",
    "employee360.approving": "Approving...",
    "employee360.approveSuccess": "Employee Approved",
    "employee360.hasBeenApproved": "has been approved successfully.",
    "employee360.approveError": "Error",
    "employee360.approveErrorDescription": "Failed to approve employee. Please try again.",
    "employee360.confirmReject": "Confirm Rejection",
    "employee360.confirmRejectDescription": "Please enter a reason for rejecting",
    "employee360.rejectReasonPlaceholder": "Enter rejection reason...",
    "employee360.rejecting": "Rejecting...",
    "employee360.rejectSuccess": "Employee Rejected",
    "employee360.hasBeenRejected": "has been rejected.",
    "employee360.rejectError": "Error",
    "employee360.rejectErrorDescription": "Failed to reject employee. Please try again.",
    "employee360.filterAll": "All",
    "employee360.filterDraft": "Draft",
    "employee360.filterSubmitted": "Submitted",
    "employee360.filterApproved": "Approved",
    "employee360.filterRejected": "Rejected",
    "employee360.noFilterResults": "No employees match the selected filter",
    "common.cancel": "Cancel",
    "dashboard.employee360": "Employee 360",
  },
  ar: {
    // Login Page
    "login.welcome": "مرحباً بك في NOC",
    "login.subtitle": "تمكين الكفاءة، ضمان الموثوقية",
    "login.email": "البريد الإلكتروني",
    "login.emailPlaceholder": "user@example.com",
    "login.password": "كلمة المرور",
    "login.passwordPlaceholder": "••••••",
    "login.forgotPassword": "نسيت كلمة المرور؟",
    "login.signIn": "تسجيل الدخول",
    "login.signingIn": "جارٍ تسجيل الدخول...",
    "login.success": "نجاح",
    "login.loginSuccessful": "تم تسجيل الدخول بنجاح!",
    "login.error": "خطأ",
    "login.loginFailed": "فشل تسجيل الدخول. يرجى التحقق من بيانات الاعتماد.",
    "login.networkError": "خطأ في الشبكة. يرجى المحاولة مرة أخرى.",
    language: "عربي",
    // Dashboard Page
    "dashboard.hello": "مرحباً،",
    "dashboard.dashboard": "لوحة التحكم",
    "dashboard.attendance": "الحضور",
    "dashboard.quickCheckIn": "تسجيل حضور سريع",
    "dashboard.scanQR": "امسح رمز QR لتسجيل الدخول/الخروج",
    "dashboard.todaysHours": "ساعات اليوم",
    "dashboard.checkedIn": "تم تسجيل الحضور",
    "dashboard.notStarted": "لم يبدأ",
    "dashboard.checkOut": "تسجيل الخروج",
    "dashboard.checkIn": "تسجيل الدخول",
    "dashboard.shift": "الوردية: 09:00 صباحاً - 06:00 مساءً",
    "dashboard.modules": "الوحدات",
    "dashboard.search": "بحث",
    "dashboard.seeAll": "عرض الكل",
    "dashboard.timeTracker": "تتبع الوقت",
    "dashboard.timeOff": "الإجازات",
    "dashboard.courses": "الدورات",
    "dashboard.expenses": "المصروفات",
    "dashboard.viewRequest": "عرض الطلب",
    "dashboard.documents": "المستندات",
    "dashboard.signedDocuments": "المستندات الموقعة",
    "dashboard.calendar": "التقويم",
    "dashboard.toDo": "المهام",
    "dashboard.timesheets": "جداول الوقت",
    "dashboard.surveys": "الاستبيانات",
    "dashboard.appraisals": "التقييمات",
    "dashboard.fleet": "الأسطول",
    "dashboard.ongoingTasks": "المهام الجارية",
    "dashboard.recentProjects": "المشاريع الأخيرة",
    "dashboard.welcome": "مرحباً",
    "dashboard.checkedInToast": "تم تسجيل الحضور",
    "dashboard.checkedInDesc": "تم تسجيل حضورك.",
    "dashboard.checkedOutToast": "تم تسجيل الخروج",
    "dashboard.checkedOutDesc": "أتمنى لك يوماً سعيداً!",
    "dashboard.timeOffCount": "4 إجازة",
    "dashboard.requestsCount": "0 طلب",
    "dashboard.expensesCount": "16 مصروف",
    "dashboard.tasksCount": "18 مهمة",
    // More Page
    "more.myProfile": "ملفي الشخصي",
    "more.myDashboard": "لوحة التحكم",
    "more.language": "اللغة",
    "more.myCourses": "دوراتي",
    "more.privacyPolicy": "سياسة الخصوصية",
    "more.termsAndConditions": "الشروط والأحكام",
    "more.logOut": "تسجيل الخروج",
    // Profile Page
    "profile.title": "الملف الشخصي",
    "profile.employeeProfile": "ملف الموظف",
    "profile.resume": "السيرة الذاتية",
    "profile.workInfo": "معلومات العمل",
    "profile.privateInfo": "المعلومات الخاصة",
    "profile.myAchievement": "إنجازاتي",
    "profile.competencies": "الكفاءات",
    "profile.workExperience": "الخبرة العملية",
    "profile.skills": "المهارات",
    "profile.privateContact": "جهة الاتصال الخاصة",
    "profile.workAddress": "عنوان العمل",
    "profile.workLocation": "موقع العمل",
    "profile.approvers": "الموافقون",
    "profile.expenses": "المصروفات",
    "profile.timeOff": "الإجازات",
    "profile.timeSheet": "ورقة الوقت",
    "profile.attendance": "الحضور",
    "profile.schedule": "الجدول الزمني",
    "profile.workingHours": "ساعات العمل",
    "profile.workLocationPlan": "خطة موقع العمل",
    "profile.timeZone": "المنطقة الزمنية",
    "profile.planning": "التخطيط",
    "profile.noRoles": "لا توجد أدوار",
    "profile.organizationChart": "الهيكل التنظيمي",
    "profile.seeAll": "عرض الكل",
    "profile.roles": "الأدوار",
    "profile.manager": "المدير",
    "profile.jobDescription": "الوصف الوظيفي",
    "profile.noJobDescription": "لا يوجد وصف وظيفي",
    "profile.privateAddress": "العنوان الخاص",
    "profile.email": "البريد الإلكتروني",
    "profile.phone": "الهاتف",
    "profile.bankAccountNumber": "رقم الحساب البنكي",
    "profile.language": "اللغة",
    "profile.homeWorkDistance": "المسافة بين المنزل والعمل",
    "profile.privateCarPlate": "لوحة السيارة الخاصة",
    "profile.familyStatus": "الحالة العائلية",
    "profile.maritalStatus": "الحالة الاجتماعية",
    "profile.maritalStatus.title": "الحالة الاجتماعية",
    "profile.maritalStatus.single": "أعزب",
    "profile.maritalStatus.married": "متزوج",
    "profile.maritalStatus.cohabitant": "ساكن قانوني",
    "profile.maritalStatus.widower": "أرمل",
    "profile.maritalStatus.divorced": "مطلق",
    "profile.numberOfChildren": "عدد الأطفال",
    "profile.emergency": "الطوارئ",
    "profile.contactName": "اسم جهة الاتصال",
    "profile.contactPhone": "هاتف جهة الاتصال",
    "profile.education": "التعليم",
    "profile.certificateLevel": "مستوى الشهادة",
    "profile.certificateLevel.graduate": "خريج",
    "profile.certificateLevel.bachelor": "بكالوريوس",
    "profile.certificateLevel.master": "ماجستير",
    "profile.certificateLevel.doctor": "دكتوراه",
    "profile.fieldOfStudy": "مجال الدراسة",
    "profile.school": "المدرسة",
    "profile.getLevelUp": "احصل على",
    "profile.xpToLevelUp": "نقطة خبرة للارتقاء!",
    "profile.badges": "الشارات",
    "profile.noBadges": "لم يتم الحصول على شارات بعد",
    "profile.current": "حالياً",
    "profile.rejectReason": "سبب الرفض",
    "profile.submissionApproved": "تمت الموافقة على طلبك من قبل مديرك.",
    "profile.submissionPending": "طلبك قيد المراجعة.",
    "profile.modified": "مُعدَّل",
    "profile.changesMade": "تم إجراء تغييرات! تذكر إرسالها للمراجعة عند الانتهاء.",
    "profile.changesSaved": "تم حفظ التغييرات محلياً",
    "profile.submittedForReview": "تم إرسال تغييراتك للمراجعة.",
    "profile.submitFailed": "فشل في إرسال التغييرات. يرجى المحاولة مرة أخرى.",
    "common.save": "حفظ",
    "common.submit": "إرسال",
    "common.submitting": "جاري الإرسال...",
    "common.success": "نجاح",
    "common.error": "خطأ",
    // Notifications Page
    "notifications.title": "الإشعارات",
    "notifications.notificationsTab": "الإشعارات",
    "notifications.modulesTab": "الوحدات",
    "notifications.appraisalToFill": "تقييم للتعبئة",
    "notifications.appraisalFor": "تقييم لـ",
    "notifications.appraisalDesc": "تم إنشاء تقييمك ويمكنك تعبئته هنا.",
    "notifications.annualLeaveRequest": "طلب إجازة سنوية جديد تم إنشاؤه بواسطة",
    "notifications.timeOff": "الإجازات",
    "notifications.employeeAppraisal": "تقييم الموظف",
    "notifications.approve": "موافقة",
    "notifications.today": "اليوم",
    "notifications.future": "مستقبلي",
    // Employee 360
    "employee360.title": "ملف الموظف 360",
    "employee360.showing": "عرض",
    "employee360.of": "من",
    "employee360.employees": "موظف",
    "employee360.loading": "جاري التحميل...",
    "employee360.loadMore": "تحميل المزيد",
    "employee360.noEmployees": "لم يتم العثور على موظفين",
    "employee360.submitted": "مُقدَّم",
    "employee360.approved": "مُوافق عليه",
    "employee360.rejected": "مرفوض",
    "employee360.review": "مراجعة",
    "employee360.approve": "موافقة",
    "employee360.reject": "رفض",
    "employee360.viewSubmission": "عرض الطلب",
    "employee360.confirmApprove": "تأكيد الموافقة",
    "employee360.confirmApproveDescription": "هل أنت متأكد أنك تريد الموافقة على طلب",
    "employee360.approving": "جاري الموافقة...",
    "employee360.approveSuccess": "تمت الموافقة على الموظف",
    "employee360.hasBeenApproved": "تمت الموافقة عليه بنجاح.",
    "employee360.approveError": "خطأ",
    "employee360.approveErrorDescription": "فشل في الموافقة على الموظف. يرجى المحاولة مرة أخرى.",
    "employee360.confirmReject": "تأكيد الرفض",
    "employee360.confirmRejectDescription": "يرجى إدخال سبب رفض",
    "employee360.rejectReasonPlaceholder": "أدخل سبب الرفض...",
    "employee360.rejecting": "جاري الرفض...",
    "employee360.rejectSuccess": "تم رفض الموظف",
    "employee360.hasBeenRejected": "تم رفضه.",
    "employee360.rejectError": "خطأ",
    "employee360.rejectErrorDescription": "فشل في رفض الموظف. يرجى المحاولة مرة أخرى.",
    "employee360.filterAll": "الكل",
    "employee360.filterDraft": "مسودة",
    "employee360.filterSubmitted": "مُقدَّم",
    "employee360.filterApproved": "مُوافق عليه",
    "employee360.filterRejected": "مرفوض",
    "employee360.noFilterResults": "لا يوجد موظفين يطابقون الفلتر المحدد",
    "common.cancel": "إلغاء",
    "dashboard.employee360": "ملف الموظف 360",
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "en" ? "ar" : "en"));
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return <LanguageContext.Provider value={{ language, toggleLanguage, t }}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
